/**
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeOcrCloud50Api);
  }
}(this, function(expect, AsposeOcrCloud50Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeOcrCloud50Api.DetectRegionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetectRegionsApi', function() {
    describe('cancelDetectRegions', function() {
      it('should call cancelDetectRegions successfully', function(done) {
        //uncomment below and update the code to test cancelDetectRegions
        //instance.cancelDetectRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDetectRegions', function() {
      it('should call getDetectRegions successfully', function(done) {
        //uncomment below and update the code to test getDetectRegions
        //instance.getDetectRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postDetectRegions', function() {
      it('should call postDetectRegions successfully', function(done) {
        //uncomment below and update the code to test postDetectRegions
        //instance.postDetectRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
