/**
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeOcrCloud50Api);
  }
}(this, function(expect, AsposeOcrCloud50Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeOcrCloud50Api.ImageProcessingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImageProcessingApi', function() {
    describe('getResultFile', function() {
      it('should call getResultFile successfully', function(done) {
        //uncomment below and update the code to test getResultFile
        //instance.getResultFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getResultTask', function() {
      it('should call getResultTask successfully', function(done) {
        //uncomment below and update the code to test getResultTask
        //instance.getResultTask(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBinarizationFile', function() {
      it('should call postBinarizationFile successfully', function(done) {
        //uncomment below and update the code to test postBinarizationFile
        //instance.postBinarizationFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postDewarpingFile', function() {
      it('should call postDewarpingFile successfully', function(done) {
        //uncomment below and update the code to test postDewarpingFile
        //instance.postDewarpingFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postSkewCorrectionFile', function() {
      it('should call postSkewCorrectionFile successfully', function(done) {
        //uncomment below and update the code to test postSkewCorrectionFile
        //instance.postSkewCorrectionFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUpsamplingFile', function() {
      it('should call postUpsamplingFile successfully', function(done) {
        //uncomment below and update the code to test postUpsamplingFile
        //instance.postUpsamplingFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
