/**
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeOcrCloud50Api);
  }
}(this, function(expect, AsposeOcrCloud50Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeOcrCloud50Api.RecognizeTableApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecognizeTableApi', function() {
    describe('cancelRecognizeTable', function() {
      it('should call cancelRecognizeTable successfully', function(done) {
        //uncomment below and update the code to test cancelRecognizeTable
        //instance.cancelRecognizeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRecognizeTable', function() {
      it('should call getRecognizeTable successfully', function(done) {
        //uncomment below and update the code to test getRecognizeTable
        //instance.getRecognizeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postRecognizeTable', function() {
      it('should call postRecognizeTable successfully', function(done) {
        //uncomment below and update the code to test postRecognizeTable
        //instance.postRecognizeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
